#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import threading
import time
import json
# import base64
import os
import random
import NIT_Node_Module
from terminalColor import bcolors

NodeUUID = "NODE-Cam" + str(random.randint(1, 1000))
# NodeUUID ="NODE-" +uuid.uuid1()

Functions = ["Image"]
NodeFunctions = ['Cams']
FS_name = []
print("::::::::::::::::::::::::::::::::::::::::::")
print("::::::::::::::::::::::::::::::::::::::::::")
print("'##::: ##::'#######::'########::'########:")
print(" ###:: ##:'##.... ##: ##.... ##: ##.....::")
print(" ####: ##: ##:::: ##: ##:::: ##: ##:::::::")
print(" ## ## ##: ##:::: ##: ##:::: ##: ######:::")
print(" ##. ####: ##:::: ##: ##:::: ##: ##...::::")
print(" ##:. ###: ##:::: ##: ##:::: ##: ##:::::::")
print(" ##::. ##:. #######:: ########:: ########:")
print("..::::..:::.......:::........:::........::")
print("::::::::::::::::::::::::::::::::::::::::::\n")

nit = NIT_Node_Module.NIT_Node(NodeUUID, Functions, NodeFunctions)


# Connect to MQTT Server for communication
def NodeToServerMQTTThread():
    # print("thread name：　" + threading.current_thread().getName())

    # callback
    nit.CallBackRxRouting = RxRouting
    print(bcolors.HEADER + '===============================================\n' + bcolors.ENDC)
    print(bcolors.HEADER + '---------------Node(%s)--->>>Server in MQTT-\n' % NodeUUID + bcolors.ENDC)
    print(bcolors.HEADER + '>>>Start connect Server %s<<<' % (
        time.asctime(time.localtime(time.time()))) + bcolors.ENDC)
    print(bcolors.HEADER + '===============================================\n' + bcolors.ENDC)
    print(bcolors.HEADER + 'Register to IoT Server successful! \n' + bcolors.ENDC)

    try:

        nit.RegisterNoode()  # 向IoT_Server註冊 TopicName = "IOTSV/REG" , 'Control': 'NODE_REG'

    except (RuntimeError, TypeError, NameError) as e:
        print(bcolors.FAIL + "[INFO]Register error." + str(e) + bcolors.ENDC)
        raise
        sys.exit(1)


########### Keyboard interactive ##############
def RxRouting(self, _obj_json_msg):  # 收到訊息會執行這個，可在這邊新增功能
    fs = nit.M2M_RxRouting(_obj_json_msg)
    if fs != "":
        FS_name.append(fs)


def loop():

    decide = "g"
    decide = input("[Trig] Enter 'img' to send image: \n")
    for FS in FS_name:

        if FS == "FS_Pic":
            print(FS)
            initMSGObj = {'TopicName': FS, 'Control': 'Img_SET', 'Source': str(NodeUUID)}
            initMSGSTR = json.dumps(initMSGObj)  # 將對象轉json(JavaScript Object Notation)
            if decide == "img":
                imageByteArray = convertImageToByteArray()
                nit.DirectMSG(FS, imageByteArray)

def convertImageToByteArray():
    with open("image_test.jpg", "rb") as image_file:
        imgByteArray = bytearray(image_file.read())
        print(bcolors.WARNING + "[Image] done" + bcolors.ENDC)
    return imgByteArray


if __name__ == "__main__":
    print(bcolors.WARNING + "[main]" + bcolors.ENDC)
    MQTT_Thread = threading.Thread(target=NodeToServerMQTTThread, name="main_thread")
    MQTT_Thread.start()

    while True:
        loop()
