#!/usr/bin/python
# -*- coding: utf-8 -*-

import sys
import threading
import time
import json
# import os
# sys.path.append(os.path.split(os.getcwd())[0])
# sys.path.append(os.path.join(os.path.split(os.getcwd())[0], 'NIT_Module'))
import NIT_Node_Module
from terminalColor import bcolors
import random
import base64

NodeUUID = "NODE-Cam" + str(random.randint(1, 1000))
# NodeUUID ="NODE-" +uuid.uuid1()

Functions = ["Image"]
NodeFunctions = ['Cam']  # ['Cam', 'GPS', 'CG']
FS_name = []


print("::::::::::::::::::::::::::::::::::::::::::")
print("::::::::::::::::::::::::::::::::::::::::::")
print("'##::: ##::'#######::'########::'########:")
print(" ###:: ##:'##.... ##: ##.... ##: ##.....::")
print(" ####: ##: ##:::: ##: ##:::: ##: ##:::::::")
print(" ## ## ##: ##:::: ##: ##:::: ##: ######:::")
print(" ##. ####: ##:::: ##: ##:::: ##: ##...::::")
print(" ##:. ###: ##:::: ##: ##:::: ##: ##:::::::")
print(" ##::. ##:. #######:: ########:: ########:")
print("..::::..:::.......:::........:::........::")
print("::::::::::::::::::::::::::::::::::::::::::\n")

nit = NIT_Node_Module.NIT_Node(NodeUUID, Functions, NodeFunctions)


# Connect to MQTT Server for communication
def NodeToServerMQTTThread():
    # print("thread name：　" + threading.current_thread().getName())

    # callback
    nit.CallBackRxRouting = RxRouting
    print(bcolors.HEADER + '===============================================\n' + bcolors.ENDC)
    print(bcolors.HEADER + '---------------Node(%s)--->>>Server in MQTT-\n' % NodeUUID + bcolors.ENDC)
    print(bcolors.HEADER + '>>>Start connect Server %s<<<' % (
        time.asctime(time.localtime(time.time()))) + bcolors.ENDC)
    print(bcolors.HEADER + '===============================================\n' + bcolors.ENDC)
    print(bcolors.HEADER + 'Register to IoT Server successful! \n' + bcolors.ENDC)

    try:

        nit.RegisterNoode()  # 向IoT_Server註冊 TopicName = "IOTSV/REG" , 'Control': 'NODE_REG'

    except (RuntimeError, TypeError, NameError) as e:
        print(bcolors.FAIL + "[INFO]Register error." + str(e) + bcolors.ENDC)
        raise
        sys.exit(1)


########### Keyboard interactive ##############
def RxRouting(self, _obj_json_msg):  # 收到訊息會執行這個，可在這邊新增功能
    fs = nit.M2M_RxRouting(_obj_json_msg)
    if fs != "":
        FS_name.append(fs)


def imageToBase64Str():
    with open("image_test.jpg", "rb") as f_img:
        # imgByteArray = bytearray(image_file.read())
        # imgByteArray = f_img.read()

        image = base64.encodebytes(f_img.read())  # binary to base64
        imgstr = image.decode('utf-8')  # bytes to str
        # imgbyte = imgstr.encode('utf-8')  # str to bytes
        print(bcolors.WARNING + "[IMAGE] Success" + bcolors.ENDC)
    return imgstr


def loop():
    decide = "g"
    decide = input("[Trig] Enter 'img' to send image: \n")
    if decide == "img":
        for FS in FS_name:
            initMSGObj = {'TopicName': FS, 'Control': 'ID', 'Source': str(NodeUUID)}

            if FS == "FS_Pic":
                # initMSGObj["IMG"] = imageToBase64Str()  # In Python 3, they removed byte support in json
                # initMSGObj['GPS'] = ['altitude', 'longitude']
                initMSGObj['GI'] = {'GPS': ['Altitude', 'Longitude'], "IMG": imageToBase64Str()}
                initMSGSTR = json.dumps(initMSGObj)  # 將對象轉json(JavaScript Object Notation)
                nit.DirectMSG(FS, initMSGSTR)  # Publish directly

if __name__ == "__main__":
    print(bcolors.WARNING + "[main]" + bcolors.ENDC)
    MQTT_Thread = threading.Thread(target=NodeToServerMQTTThread, name="main_thread")
    MQTT_Thread.start()

    while True:
        loop()
